services:
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - traefik_wordpress
      - traefik_phpmyadmin
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.lets-encr.acme.httpchallenge=true"
      - "--certificatesresolvers.lets-encr.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.lets-encr.acme.email=your@email.com"
      - "--certificatesresolvers.lets-encr.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    restart: always

  db:
    image: mariadb:latest
    container_name: db
    networks:
      - db_wordpress
      - db_phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_db_password
    secrets:
      - mariadb_root_password
      - wordpress_db_password

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    networks:
      - traefik_wordpress
      - db_wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wordpress_data:/var/www/html
    secrets:
      - wordpress_db_password
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_wordpress"
      - "traefik.http.routers.wordpress.rule=Host(`domain_placeholder`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=lets-encr"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    networks:
      - traefik_phpmyadmin
      - db_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_phpmyadmin"
      - "traefik.http.routers.phpmyadmin.rule=Host(`domain_placeholder`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=lets-encr"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

volumes:
  db_data:
  wordpress_data:
  letsencrypt:

networks:
  traefik_wordpress:
    name: traefik_wordpress
  traefik_phpmyadmin:
    name: traefik_phpmyadmin
  db_wordpress:
    name: db_wordpress
  db_phpmyadmin:
    name: db_phpmyadmin

secrets:
  mariadb_root_password:
    file: ./secrets/mariadb_root_password
  wordpress_db_password:
    file: ./secrets/wordpress_db_password