---
- name: Set up cloud-1
  hosts: webservers
  become: true
  tasks:
    - name: Update package cache and upgrade all packages
      apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        clean: true

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - ufw
        state: latest

    - name: Configure UFW
      ufw:
        default: deny
        rule: allow
        proto: tcp
        port: 22,80,443
        state: enabled

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Make GPG key readable
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: 'a+r'

    - name: Add Docker official repository (modern deb822 format)
      copy:
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: {{ ansible_facts["distribution_release"] }}
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc
        dest: /etc/apt/sources.list.d/docker.sources
        mode: '0644'

    - name: Force apt update after repo change
      shell:
        cmd: apt update

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Ensure Docker is started and enabled on boot
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy docker-compose.yaml
      copy:
        src: ./docker-compose.yaml
        dest: /home/{{ ansible_user }}/docker-compose.yaml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Create secrets dir
      file:
        path: /home/{{ ansible_user }}/secrets
        state: directory
        mode: 0400

    - name: Deploy mariadb root password
      copy:
        content: "{{ mariadb_root_password }}"
        dest: /home/{{ ansible_user }}/secrets/mariadb_root_password
        mode: 0444

    - name: Deploy wordpress db password
      copy:
        content: "{{ wordpress_db_password }}"
        dest: /home/{{ ansible_user }}/secrets/wordpress_db_password
        mode: 0444

    - name: Start stack
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}/
        state: present